// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGA5JhBmBVSp2Yv7_y_0jvxgsAzaO2wg',
    appId: '1:993217397795:web:f5a1e66aa70ffe6928dd96',
    messagingSenderId: '993217397795',
    projectId: 'app-cotizador-38087',
    authDomain: 'app-cotizador-38087.firebaseapp.com',
    storageBucket: 'app-cotizador-38087.firebasestorage.app',
    measurementId: 'G-T0C0W7DZ18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnoz3wYJ0u9hxDmRjTXDbVaw7j0PJoSA',
    appId: '1:993217397795:android:03e8d2171735c4c728dd96',
    messagingSenderId: '993217397795',
    projectId: 'app-cotizador-38087',
    storageBucket: 'app-cotizador-38087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30eT45jOPo7C3_cHJ4tc61G1pycoX9cA',
    appId: '1:993217397795:ios:4bce04ae656e286f28dd96',
    messagingSenderId: '993217397795',
    projectId: 'app-cotizador-38087',
    storageBucket: 'app-cotizador-38087.firebasestorage.app',
    iosBundleId: 'com.example.cotizadorWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30eT45jOPo7C3_cHJ4tc61G1pycoX9cA',
    appId: '1:993217397795:ios:4bce04ae656e286f28dd96',
    messagingSenderId: '993217397795',
    projectId: 'app-cotizador-38087',
    storageBucket: 'app-cotizador-38087.firebasestorage.app',
    iosBundleId: 'com.example.cotizadorWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxGA5JhBmBVSp2Yv7_y_0jvxgsAzaO2wg',
    appId: '1:993217397795:web:a5c8795ddc23fccf28dd96',
    messagingSenderId: '993217397795',
    projectId: 'app-cotizador-38087',
    authDomain: 'app-cotizador-38087.firebaseapp.com',
    storageBucket: 'app-cotizador-38087.firebasestorage.app',
    measurementId: 'G-Y2J2TKHKCR',
  );
}
